import './global.css';
import React  from 'react';
import { TopMenu } from "./components/TopMenu";
import { AntdRegistry } from '@ant-design/nextjs-registry';

export const metadata = {
  title: 'Welcome to client if openhema 2.0',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
      <AntdRegistry>
        <TopMenu/>
        {children}
      </AntdRegistry>
      </body>
    </html>
  );
}
